groups:
  - id: exception
    prefix: exception
    brief: >
      This document defines the attributes used to
      report a single exception associated with a span.
    attributes:
      - id: type
        type: string
        brief: >
          The type of the exception (its fully-qualified class name, if applicable).
          The dynamic type of the exception should be preferred over the static type
          in languages that support it.
        examples: ["java.net.ConnectException", "OSError"]
      - id: message
        type: string
        brief: The exception message.
        examples: ["Division by zero", "Can't convert 'int' object to str implicitly"]
      - id: stacktrace
        type: string
        brief: >
          A stacktrace as a string in the natural representation for the language runtime.
          The representation is to be determined and documented by each language SIG.
        examples: 'Exception in thread "main" java.lang.RuntimeException: Test exception\n
        at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\n
        at com.example.GenerateTrace.methodA(GenerateTrace.java:9)\n
        at com.example.GenerateTrace.main(GenerateTrace.java:5)'
      - id: escaped
        type: boolean
        brief: >
          SHOULD be set to true if the exception event is recorded at a point where
          it is known that the exception is escaping the scope of the span.
        note: |-
          An exception is considered to have escaped (or left) the scope of a span,
          if that span is ended while the exception is still logically "in flight".
          This may be actually "in flight" in some languages (e.g. if the exception
          is passed to a Context manager's `__exit__` method in Python) but will
          usually be caught at the point of recording the exception in most languages.

          It is usually not possible to determine at the point where an exception is thrown
          whether it will escape the scope of a span.
          However, it is trivial to know that an exception
          will escape, if one checks for an active exception just before ending the span,
          as done in the [example above](#exception-end-example).

          It follows that an exception may still escape the scope of the span
          even if the `exception.escaped` attribute was not set or set to false,
          since the event might have been recorded at a time where it was not
          clear whether the exception will escape.

    constraints:
      - any_of:
          - "exception.type"
          - "exception.message"
